/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.br.rentdrive.model.gui.view;

import com.br.rentdrive.model.dao.ClienteDAO;
import com.br.rentdrive.model.dao.CompraDAO;
import com.br.rentdrive.model.dao.VeiculoDAO;
import com.br.rentdrive.model.entities.Clientes;
import com.br.rentdrive.model.entities.Veiculos;
import com.br.rentdrive.model.entities.contract.Compras;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author rober
 */
public class CadastrarCompra extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarCompra
     */
    public CadastrarCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelRentDrive = new javax.swing.JLabel();
        LabelRentDrive1 = new javax.swing.JLabel();
        LabelNome = new javax.swing.JLabel();
        LabelCidade = new javax.swing.JLabel();
        LabelEndereco = new javax.swing.JLabel();
        LabelEstado = new javax.swing.JLabel();
        txtClienteId = new javax.swing.JTextField();
        txtDataRetirada = new javax.swing.JTextField();
        txtVeiculoId = new javax.swing.JTextField();
        bttnCadastrar = new javax.swing.JButton();
        LabelEstado1 = new javax.swing.JLabel();
        LabelEndereco1 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de compra");

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        LabelRentDrive.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LabelRentDrive.setForeground(new java.awt.Color(255, 255, 255));
        LabelRentDrive.setText("Cadastro de compra");

        LabelRentDrive1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelRentDrive1.setForeground(new java.awt.Color(255, 255, 255));
        LabelRentDrive1.setText("RentDrive");

        LabelNome.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LabelNome.setForeground(new java.awt.Color(255, 255, 255));
        LabelNome.setText("Cliente id");

        LabelCidade.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LabelCidade.setForeground(new java.awt.Color(255, 255, 255));
        LabelCidade.setText("Status");

        LabelEndereco.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LabelEndereco.setForeground(new java.awt.Color(255, 255, 255));

        LabelEstado.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LabelEstado.setForeground(new java.awt.Color(255, 255, 255));
        LabelEstado.setText("Veiculo id");

        txtClienteId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteIdActionPerformed(evt);
            }
        });

        txtDataRetirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataRetiradaActionPerformed(evt);
            }
        });

        txtVeiculoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVeiculoIdActionPerformed(evt);
            }
        });

        bttnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bttnCadastrar.setText("Cadastrar");
        bttnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCadastrarActionPerformed(evt);
            }
        });

        LabelEstado1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LabelEstado1.setForeground(new java.awt.Color(255, 255, 255));
        LabelEstado1.setText("Data de retirada");

        LabelEndereco1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LabelEndereco1.setForeground(new java.awt.Color(255, 255, 255));
        LabelEndereco1.setText("Valor");

        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(LabelCidade)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelEndereco)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelEndereco1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelEstado1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelNome)
                                    .addComponent(LabelEstado))
                                .addGap(112, 112, 112)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVeiculoId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelRentDrive)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelRentDrive1)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bttnCadastrar)
                        .addGap(173, 173, 173))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelRentDrive1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelRentDrive)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNome)
                            .addComponent(txtClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelEstado)
                            .addComponent(txtVeiculoId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelEstado1)
                            .addComponent(txtDataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LabelCidade))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelEndereco1)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LabelEndereco)
                .addGap(18, 18, 18)
                .addComponent(bttnCadastrar)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteIdActionPerformed

    private void txtDataRetiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataRetiradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataRetiradaActionPerformed

    private void txtVeiculoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVeiculoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVeiculoIdActionPerformed

    private void bttnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCadastrarActionPerformed
        String clienteId = txtClienteId.getText();
        String veiculoId = txtVeiculoId.getText();
        String dataRetiradaStg = txtDataRetirada.getText();
        String valor = txtValor.getText();

        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date dataRetirada = dateFormat.parse(dataRetiradaStg);

            ClienteDAO clienteDAO = new ClienteDAO();
            VeiculoDAO veiculoDAO = new VeiculoDAO();
            Clientes cliente = clienteDAO.findById(Integer.parseInt(clienteId));
            Veiculos veiculo = veiculoDAO.findById(Integer.parseInt(veiculoId));
            Compras compra = new Compras();

            compra.setClienteId(cliente);
            compra.setVeiculoId(veiculo);
            compra.setDataRetirada(dataRetirada);
            compra.setValor(Double.parseDouble(valor));

            CompraDAO dao = new CompraDAO();
            dao.cadastrar(compra);

        } catch (ParseException e) {
              JOptionPane.showMessageDialog(this, "Data incorreta.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bttnCadastrarActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCidade;
    private javax.swing.JLabel LabelEndereco;
    private javax.swing.JLabel LabelEndereco1;
    private javax.swing.JLabel LabelEstado;
    private javax.swing.JLabel LabelEstado1;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelRentDrive;
    private javax.swing.JLabel LabelRentDrive1;
    private javax.swing.JButton bttnCadastrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtClienteId;
    private javax.swing.JTextField txtDataRetirada;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtVeiculoId;
    // End of variables declaration//GEN-END:variables
}
