/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.br.rentdrive.model.gui.view;

import com.br.rentdrive.model.dao.ClienteDAO;
import com.br.rentdrive.model.dao.PagamentoDAO;
import com.br.rentdrive.model.dao.VeiculoDAO;
import com.br.rentdrive.model.entities.Clientes;
import com.br.rentdrive.model.entities.Veiculos;
import com.br.rentdrive.model.entities.contract.Pagamentos;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author rober
 */
public class CadastrarPagamento extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarPagamento
     */
    public CadastrarPagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelRentDrive = new javax.swing.JLabel();
        LabelRentDrive1 = new javax.swing.JLabel();
        LabelNome = new javax.swing.JLabel();
        LabelCidade = new javax.swing.JLabel();
        LabelEndereco = new javax.swing.JLabel();
        LabelEstado = new javax.swing.JLabel();
        txtClienteId = new javax.swing.JTextField();
        txtVeiculoId = new javax.swing.JTextField();
        txtDataPagamento = new javax.swing.JTextField();
        bttnCadastrar = new javax.swing.JButton();
        LabelEstado1 = new javax.swing.JLabel();
        LabelEndereco1 = new javax.swing.JLabel();
        comboxTipo = new javax.swing.JComboBox<>();
        comboxStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de pagamento");

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        LabelRentDrive.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LabelRentDrive.setForeground(new java.awt.Color(255, 255, 255));
        LabelRentDrive.setText("Cadastro de pagamento");

        LabelRentDrive1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelRentDrive1.setForeground(new java.awt.Color(255, 255, 255));
        LabelRentDrive1.setText("RentDrive");

        LabelNome.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LabelNome.setForeground(new java.awt.Color(255, 255, 255));
        LabelNome.setText("Cliente id");

        LabelCidade.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LabelCidade.setForeground(new java.awt.Color(255, 255, 255));
        LabelCidade.setText("Status");

        LabelEndereco.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LabelEndereco.setForeground(new java.awt.Color(255, 255, 255));
        LabelEndereco.setText("Tipo");

        LabelEstado.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LabelEstado.setForeground(new java.awt.Color(255, 255, 255));
        LabelEstado.setText("Data do pagamento");

        txtClienteId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteIdActionPerformed(evt);
            }
        });

        txtVeiculoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVeiculoIdActionPerformed(evt);
            }
        });

        txtDataPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataPagamentoActionPerformed(evt);
            }
        });

        bttnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bttnCadastrar.setText("Cadastrar");
        bttnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCadastrarActionPerformed(evt);
            }
        });

        LabelEstado1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LabelEstado1.setForeground(new java.awt.Color(255, 255, 255));
        LabelEstado1.setText("Veiculo id");

        LabelEndereco1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LabelEndereco1.setForeground(new java.awt.Color(255, 255, 255));
        LabelEndereco1.setText("Status");

        comboxTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debito", "Credito", "Pix" }));

        comboxStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pago", "Pendente", "Não pago" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelRentDrive)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelRentDrive1)
                        .addGap(163, 163, 163))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelEstado1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtVeiculoId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelNome)
                                .addGap(116, 116, 116)
                                .addComponent(txtClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelEstado)
                                .addGap(18, 18, 18)
                                .addComponent(txtDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(LabelCidade)
                                .addGap(47, 47, 47))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelEndereco1)
                                .addGap(65, 65, 65))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(bttnCadastrar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelRentDrive1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelRentDrive)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNome)
                            .addComponent(txtClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelEstado)
                            .addComponent(txtDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelEstado1)
                            .addComponent(txtVeiculoId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LabelCidade))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEndereco)
                    .addComponent(LabelEndereco1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboxTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGap(57, 57, 57)
                .addComponent(bttnCadastrar)
                .addGap(87, 87, 87))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteIdActionPerformed

    private void txtVeiculoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVeiculoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVeiculoIdActionPerformed

    private void txtDataPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataPagamentoActionPerformed

    private void bttnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCadastrarActionPerformed
        String clienteId = txtClienteId.getText();
        String dataPagamentoString = txtDataPagamento.getText();
        String veiculoId = txtVeiculoId.getText();
        String tipo = (String)comboxTipo.getSelectedItem();
        String status = (String)comboxStatus.getSelectedItem();
        
           try {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date dataPagamento = dateFormat.parse(dataPagamentoString);
        

        ClienteDAO clienteDAO = new ClienteDAO();
        VeiculoDAO veiculoDAO = new VeiculoDAO();


        Clientes cliente = clienteDAO.findById(Integer.parseInt(clienteId));
        Veiculos veiculo = veiculoDAO.findById(Integer.parseInt(veiculoId));
        
        Pagamentos novoPagamento = new Pagamentos();
        novoPagamento.setCliente_id(cliente);
        novoPagamento.setData_pagamento(dataPagamento);
        novoPagamento.setVeiculo_id(veiculo);
        novoPagamento.setTipo(tipo);
        novoPagamento.setStatus(status);
        
        PagamentoDAO pagamentoDAO = new PagamentoDAO();
        pagamentoDAO.cadastrar(novoPagamento); 
        JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso.");
       
        this.dispose();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Dados incorretos.", "Aviso", JOptionPane.WARNING_MESSAGE);
    }




    }//GEN-LAST:event_bttnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCidade;
    private javax.swing.JLabel LabelEndereco;
    private javax.swing.JLabel LabelEndereco1;
    private javax.swing.JLabel LabelEstado;
    private javax.swing.JLabel LabelEstado1;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelRentDrive;
    private javax.swing.JLabel LabelRentDrive1;
    private javax.swing.JButton bttnCadastrar;
    private javax.swing.JComboBox<String> comboxStatus;
    private javax.swing.JComboBox<String> comboxTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtClienteId;
    private javax.swing.JTextField txtDataPagamento;
    private javax.swing.JTextField txtVeiculoId;
    // End of variables declaration//GEN-END:variables
}
