package application;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class CadastroConsulta extends javax.swing.JFrame {

    private TabelaConsulta tabelaConsulta;

    public CadastroConsulta() {
    }

    public CadastroConsulta(TabelaConsulta tabelaConsulta) {
        initComponents();
        this.tabelaConsulta = tabelaConsulta;
    }

    private boolean validarData(String data) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yy");
        sdf.setLenient(false);
        try {
            Date dataConsulta = sdf.parse(data);
            if (dataConsulta.before(new Date())) {
                JOptionPane.showMessageDialog(this, "A data da consulta não pode ser no passado.");
            }
            return true;
        } catch (ParseException e) {
            return false;
        }

    }

    private boolean validarNome(String nome) {
        return nome.matches("^[a-zA-Z ]+$");
    }

    private boolean validarFormatoCPF(String cpf) {
        return cpf.matches("\\d{11}");
    }

    private boolean validarFormatoTelefone(String telefone) {
        String apenasDigitos = telefone.replaceAll("[^\\d]", "");

        return apenasDigitos.matches("\\d{9}|\\d{11,12}");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCPF = new javax.swing.JTextField();
        jLabelTel = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelDate = new javax.swing.JLabel();
        jLabelCadastrarT = new javax.swing.JLabel();
        jCheckBoxPac = new javax.swing.JCheckBox();
        jTextFieldTel = new javax.swing.JTextField();
        jButtonCadas = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelTel.setText("Telefone:");

        jLabelCPF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelCPF.setText("CPF:");

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabelDate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelDate.setText("Data da Consulta:");

        jLabelCadastrarT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCadastrarT.setText("Cadastrar Consulta");

        jCheckBoxPac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxPac.setText("Já é paciente");

        jButtonCadas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonCadas.setText("Cadastrar");
        jButtonCadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadasActionPerformed(evt);
            }
        });

        jLabelName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelName.setText("Nome do(a) Paciente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButtonCadas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCadastrarT)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelTel)
                        .addComponent(jLabelName)
                        .addComponent(jLabelCPF)
                        .addComponent(jLabelDate)
                        .addComponent(jCheckBoxPac)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jTextFieldTel))
                    .addComponent(jTextFieldCPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelCadastrarT)
                        .addGap(28, 28, 28)
                        .addComponent(jLabelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTel)
                            .addComponent(jTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCPF)
                            .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDate)
                            .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxPac)
                        .addGap(41, 41, 41)))
                .addComponent(jButtonCadas)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonCadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadasActionPerformed
        try {
            String name = jTextFieldName.getText();
            String telefone = jTextFieldTel.getText();
            String cpf = jTextFieldCPF.getText();
            String dataConsulta = jTextFieldDate.getText();

            if (!validarNome(name)) {
                JOptionPane.showMessageDialog(this, "Nome inválido. Insira um nome válido.");
                return;
            }

            if (!validarFormatoTelefone(telefone)) {
                JOptionPane.showMessageDialog(this, "Telefone inválido. Insira um telefone válido.");
                return;
            }

            if (!validarFormatoCPF(cpf)) {
                JOptionPane.showMessageDialog(this, "CPF inválido. Insira um CPF válido.");
                return;
            }
            if (!validarData(dataConsulta)) {
                JOptionPane.showMessageDialog(this, "Data inválida. Insira uma data válida no formato dd/MM/aa.");
                return;
            }

            boolean ehPaciente = jCheckBoxPac.isSelected();
            Consulta novaConsulta = new Consulta(name, cpf, telefone, dataConsulta, ehPaciente);
            tabelaConsulta.incluirConsulta(novaConsulta);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "[ERRO] Digite valores numéricos válidos.");
        } finally {
            dispose();
        }
    }//GEN-LAST:event_jButtonCadasActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed

    }//GEN-LAST:event_jTextFieldNameActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadas;
    private javax.swing.JCheckBox jCheckBoxPac;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCadastrarT;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldTel;
    // End of variables declaration//GEN-END:variables
}
